### ISSUE TITLE
3.0 Roadmap

### ISSUE THREAD

**Issue by mikeastock** [feedjira/feedjira#382]
- [x] Configure in a idiomatic way
- [x] Support custom parser 9461eec369e2a417a567410dd6fb63eccf16b8e6
- [x] Support parser order #370 
- [ ] Raise exceptions for failed parsing
- [x] Fetching XML should not be a part of Feedjira #381 
- [x] Move `parse` and `paser_for_xml` https://github.com/feedjira/feedjira/pull/384
Originally from: https://github.com/feedjira/feedjira/issues/370
